trabajo_final/final_challenge/urls.py
"""Final challenge views"""
from django.urls import path
#Consultas
from .views import import_data
from .views import query_one
from .views import query_two
from .views import query_three
from .views import query_four
from .views import query_five
from .views import query_six
from .views import query_seven
from .views import query_eight
from .views import query_nine

app_name = 'final_challenge'

urlpatterns = [
    path('', import_data, name='import_data'),
    path('query_one/', query_one, name='query_one'),
    path('query_two/', query_two, name='query_two'),
    path('query_three', query_three, name='query_three'),
    path('query_four/', query_four, name='query_four'),
    path('query_five/', query_five, name='query_five'),
    path('query_six/', query_six, name='query_six'),
    path('query_seven/', query_seven, name='query_seven'),
    path('query_eight/', query_eight, name='query_eight'),
    path('query_nine/', query_nine, name='query_nine'),
]

trabajo_final/trabajo_final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('final_challenge.urls')),
]

trabajo_final/final_challenge/models.py
from django.db import models

# Create your models here.

trabajo_final/final_challenge/views.py
"""Views de final_challenge"""
from django.shortcuts import render

from .services import get_import_data

from .services import get_query_one
from .services import get_query_four
from .services import get_query_two
from .services import get_query_three
from .services import get_query_three_pais_cadena
from .services import get_query_three_pais
from .services import get_query_three_cadena
from .services import get_query_five
from .services import get_query_six
from .services import get_query_seven
from .services import get_query_eight
from .services import get_query_nine

from .services import get_fecha_pelicula
from .services import get_fecha_pais_pelicula


# Create your views here.

def import_data(request):
    """importa los datos"""
    if request.method == 'POST':
        context = {
            'import_data': get_import_data()
        }
        return render(request, 'final_challenge/templates/import_data.html', context)
    return render(request, 'final_challenge/templates/import_data.html')

def query_one(request):
    """Formulario para ingresar los parametros para mostrar template table_one"""
    if request.method == 'POST':
        fecha_inicio = request.POST['inputFechaInicio']
        fecha_final = request.POST['inputFechaFinal']
        context = {
            'query_one': get_query_one(
                fecha_inicio[-5:],
                fecha_final[-5:],
                fecha_final[:4]
            ),
            'fecha_inicio': fecha_inicio,
            'fecha_final': fecha_final,
        }
        return render(request, 'final_challenge/templates/tables/table_one.html', context)
    return render(request, 'final_challenge/templates/tables/table_one.html')


def query_two(request):
    """Mostrar el total de personas de los 5 paises que visitaron el cine en la semana"""
    if request.method == 'POST':
        fecha_inicio = request.POST['inputFechaInicio']
        fecha_final = request.POST['inputFechaFinal']
        context = {
            'query_two': get_query_two(
                fecha_inicio[-5:],
                fecha_final[-5:],
                fecha_final[:4]
            ),
            'fecha_inicio': fecha_inicio,
            'fecha_final': fecha_final,
        }
        return render(request, 'final_challenge/templates/tables/table_two.html', context)
    return render(request, 'final_challenge/templates/tables/table_two.html')


def query_three(request):
    """Mostrar el total de personas de los 5 paises que visitaron el cine en la semana"""
    if request.method == 'POST':
        fecha_inicio = request.POST['inputFechaInicio']
        fecha_final = request.POST['inputFechaFinal']
        if (request.POST.get('inputTextPais', False) and
            request.POST.get('inputTextCadena', False)):
            pais = request.POST['inputTextPais']
            cadena = request.POST['inputTextCadena']
            context = {
                'query_three': get_query_three_pais_cadena(
                    fecha_inicio[-5:],
                    fecha_final[-5:],
                    fecha_final[:4],
                    pais,
                    cadena,
                ),
                'fecha_inicio': fecha_inicio,
                'fecha_final': fecha_final,
                'pais': pais,
                'cadena': cadena,
            }
        elif request.POST.get('inputTextPais', False):
            pais = request.POST['inputTextPais']
            context = {
                'query_three': get_query_three_pais(
                    fecha_inicio[-5:],
                    fecha_final[-5:],
                    fecha_final[:4],
                    pais,
                ),
                'fecha_inicio': fecha_inicio,
                'fecha_final': fecha_final,
                'pais': pais,
            }
        elif request.POST.get('inputTextCadena', False):
            print('hola')
            cadena = request.POST['inputTextCadena']
            context = {
                'query_three': get_query_three_cadena(
                    fecha_inicio[-5:],
                    fecha_final[-5:],
                    fecha_final[:4],
                    cadena,
                ),
                'fecha_inicio': fecha_inicio,
                'fecha_final': fecha_final,
                'cadena': cadena,
            }
        else:
            context = {
                'query_three': get_query_three(
                    fecha_inicio[-5:],
                    fecha_final[-5:],
                    fecha_final[:4]
                ),
                'fecha_inicio': fecha_inicio,
                'fecha_final': fecha_final,
            }
        return render(request, 'final_challenge/templates/tables/table_three.html', context)
    return render(request, 'final_challenge/templates/tables/table_three.html')


def query_four(request):
    """"El total de personas que vieron cada pelicula en centroamerica"""
    if request.method == 'POST':
        pelicula = request.POST['inputTextPelicula']
        print(pelicula)
        context = {
            'query_four': get_query_four(pelicula),
            'query_five': get_query_five(pelicula),
            'pelicula': pelicula,
        }
        return render(request, 'final_challenge/templates/tables/table_four.html', context)

    return render(request, 'final_challenge/templates/tables/table_four.html')


def query_five(requests):
    """El total de personas que vieron cada pelicula en centroamerica
    por cadena de cine"""
    context = {
        #'query_five': get_query_five()
    }
    return render(requests, 'final_challenge/templates/tables/table_five.html', context)


def query_six(request):
    """El total de personas que vieron cada pelicula en centroamerica
    por cadena de cine pero en porcentaje"""
    if request.method == 'POST':
        pelicula = request.POST['inputTextPelicula']
        context = {
            'query_six': get_query_six(pelicula),
            'pelicula': pelicula
        }
        return render(request, 'final_challenge/templates/tables/table_six.html', context)
    return render(request, 'final_challenge/templates/tables/table_six.html')


def query_seven(request):
    """Mostrar para cada pelicula el total de personas que acudieron a verla en la
    semana por pais y ordenarla de la más vista a la menos vista"""
    if request.method == 'POST':
        fecha_inicio = request.POST['inputFechaInicio']
        fecha_final = request.POST['inputFechaFinal']
        if request.POST.get('inputTextPelicula', False):
            pelicula = request.POST['inputTextPelicula']
            context = {
                'query_seven': get_query_seven(
                    fecha_inicio[-5:],
                    fecha_final[-5:],
                    fecha_final[:4],
                    pelicula
                ),
                'fecha_inicio': fecha_inicio,
                'fecha_final': fecha_final,
                'pelicula': pelicula,
            }
            return render(request, 'final_challenge/templates/tables/table_seven.html', context)
        else:
            context = {
                'movies': get_fecha_pelicula(
                    fecha_inicio[-5:],
                    fecha_final[-5:],
                    fecha_final[:4],
                ),
                'fecha_inicio': fecha_inicio,
                'fecha_final': fecha_final,
            }
            return render(request, 'final_challenge/templates/tables/table_seven.html', context)
    return render(request, 'final_challenge/templates/tables/table_seven.html')


def query_eight(request):
    """Total de personas por cadena de cine, por pais, por semana"""
    if request.method == 'POST':
        fecha_inicio = request.POST['inputFechaInicio']
        fecha_final = request.POST['inputFechaFinal']
        pais = request.POST['inputPais']
        pelicula = request.POST['inputTextPelicula']
        context = {
            'query_eight': get_query_eight(
                fecha_inicio[-5:],
                fecha_final[-5:],
                fecha_final[:4],
                pais,
                pelicula,
            ),
            'fecha_inicio': fecha_inicio,
            'fecha_final': fecha_final,
            'pais': pais,
            'pelicula': pelicula,
        }
        return render(request, 'final_challenge/templates/tables/table_eight.html', context)
    return render(request, 'final_challenge/templates/tables/table_eight.html')


def query_nine(request):
    """Total de personas por cadena de cine, por pais, por semana en porcentaje"""
    if request.method == 'POST':
        fecha_inicio = request.POST['inputFechaInicio']
        fecha_final = request.POST['inputFechaFinal']
        pais = request.POST['inputPais']
        if request.POST.get('inputTextPelicula', False):
            pelicula = request.POST['inputTextPelicula']
            context = {
                'query_nine': get_query_nine(
                    fecha_inicio[-5:],
                    fecha_final[-5:],
                    fecha_final[:4],
                    pais,
                    pelicula,
                ),
                'fecha_inicio': fecha_inicio,
                'fecha_final': fecha_final,
                'pais': pais,
                'pelicula': pelicula,
            }
        else:
            context = {
                'movies': get_fecha_pais_pelicula(
                    fecha_inicio[-5:],
                    fecha_final[-5:],
                    fecha_final[:4],
                    pais,
                ),
                'fecha_inicio': fecha_inicio,
                'fecha_final': fecha_final,
                'pais': pais,
            }
        return render(request, 'final_challenge/templates/tables/table_nine.html', context)
    return render(request, 'final_challenge/templates/tables/table_nine.html')

trabajo_final/final_challenge/templates/final_challenge/templates/includes/fixed-plugin.html
  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Background</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger background-color">
            <div class="badge-colors text-center">
              <span class="badge filter badge-primary active" data-color="primary"></span>
              <span class="badge filter badge-info" data-color="blue"></span>
              <span class="badge filter badge-success" data-color="green"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="adjustments-line text-center color-change">
          <span class="color-label">LIGHT MODE</span>
          <span class="badge light-badge mr-2"></span>
          <span class="badge dark-badge ml-2"></span>
          <span class="color-label">DARK MODE</span>
        </li>
        <li class="button-container">

          <a href="https://appseed.us/jinja-template" 
             target="_blank" rel="noopener noreferrer" 
             class="btn btn-primary btn-block btn-round">More Templates</a>

          <a href="https://appseed.us/admin-dashboards" 
             target="_blank" rel="noopener noreferrer" 
             class="btn btn-default btn-block btn-round">
            More Dashboards
          </a>
        </li>
        <li class="header-title">
          Coded by <a class="text-white" 
                      target="_blank" rel="noopener noreferrer" 
                      href="https://appseed.us">AppSeed</a>
                   
        </li>
        <li>
          <br />
        </li>
      </ul>

    </div>
  </div>
  

trabajo_final/final_challenge/templates/final_challenge/templates/includes/footer.html
      <footer class="footer">
        <div class="container-fluid">
          <ul class="nav">
            <li class="nav-item">
              <a target="_blank" rel="noopener noreferrer"
                 href="https://appseed.us/admin-dashboards/django-dashboard-black" class="nav-link">
                Django Dashboard Black
              </a>
            </li>
          </ul>
          <div class="copyright">
            &copy; <a target="_blank" rel="sponsored noopener noreferrer" 
                      href="https://bit.ly/3fKQZaL">Creative-Tim</a> 
            - coded by <a target="_blank" rel="noopener noreferrer" href="https://appseed.us">AppSeed</a>
          </div>
        </div>
      </footer>
      

trabajo_final/final_challenge/templates/final_challenge/templates/includes/navigation-rtl.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">RTL</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav  mr-auto">
              <li class="search-bar input-group">
                <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                  <span class="d-lg-none d-md-block">Search</span>
                </button>
              </li>
              <li class="dropdown nav-item">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="notification d-none d-lg-block d-xl-block"></div>
                  <i class="tim-icons icon-sound-wave"></i>
                  <p class="d-lg-none">
                    Notifications
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                  <li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded to your email</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You have 5 more tasks</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your friend Michael is in town</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another notification</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another one</a></li>
                </ul>
              </li>
              <li class="dropdown nav-item">
                <a href="{% url 'logout' %}" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="/static/assets/img/anime3.png" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Profile</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Settings</a></li>
                  <li class="dropdown-divider"></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Log out</a></li>
                </ul>
              </li>
              <li class="separator d-lg-none"></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

trabajo_final/final_challenge/templates/final_challenge/templates/includes/navigation.html
{% load static %}
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">
              Free Dashboard
            </a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">

            <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}

              <li class="search-bar input-group">
                <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                  <span class="d-lg-none d-md-block">Search</span>
                </button>
              </li>
              <li class="dropdown nav-item">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="notification d-none d-lg-block d-xl-block"></div>
                  <i class="tim-icons icon-sound-wave"></i>
                  <p class="d-lg-none">
                    Notifications
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                  <li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded to your email</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You have 5 more tasks</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your friend Michael is in town</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another notification</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another one</a></li>
                </ul>
              </li>
              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="{% static 'final_challenge/static/assets/img/anime3.png' %}" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="" class="nav-item dropdown-item">Profile</a></li>
                  <li class="dropdown-divider"></li>
                  <li class="nav-link"><a href="" class="nav-item dropdown-item">Log out</a></li>
                </ul>
              </li>
              <li class="separator d-lg-none"></li>

            {% endif %}  
            </ul>

          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

trabajo_final/final_challenge/templates/final_challenge/templates/includes/scripts-sidebar.html
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');
        $navbar = $('.navbar');
        $main_panel = $('.main-panel');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');
        sidebar_mini_active = true;
        white_color = false;

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();



        $('.fixed-plugin a').click(function(event) {
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .background-color span').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data', new_color);
          }

          if ($main_panel.length != 0) {
            $main_panel.attr('data', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data', new_color);
          }
        });

        $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            sidebar_mini_active = false;
            blackDashboard.showSidebarMessage('Sidebar mini deactivated...');
          } else {
            $('body').addClass('sidebar-mini');
            sidebar_mini_active = true;
            blackDashboard.showSidebarMessage('Sidebar mini activated...');
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);
        });

        $('.switch-change-color input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (white_color == true) {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').removeClass('white-content');
            }, 900);
            white_color = false;
          } else {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').addClass('white-content');
            }, 900);

            white_color = true;
          }


        });

        $('.light-badge').click(function() {
          $('body').addClass('white-content');
        });

        $('.dark-badge').click(function() {
          $('body').removeClass('white-content');
        });
      });
    });
  </script>
  

trabajo_final/final_challenge/templates/final_challenge/templates/includes/scripts.html
  <!--   Core JS Files   -->
  <script src="/static/assets/js/core/jquery.min.js"></script>
  <script src="/static/assets/js/core/popper.min.js"></script>
  <script src="/static/assets/js/core/bootstrap.min.js"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!-- Chart JS -->
  <script src="/static/assets/js/plugins/chartjs.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="/static/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/static/assets/js/black-dashboard.min.js?v=1.0.0"></script><!-- Black Dashboard DEMO methods, don't include it in your project! -->
  <script src="/static/assets/demo/demo.js"></script>
  

trabajo_final/final_challenge/templates/final_challenge/templates/includes/sidebar.html
    <div class="sidebar">
      <div class="sidebar-wrapper">
        <div class="logo">
          <a href="{% url 'final_challenge:import_data' %}" class="simple-text logo-normal">
            Importar Datos
          </a>
        </div>

        <ul class="nav">
        {% if request.user.is_authenticated %}

          <li class="{% if 'index' in segment %} active {% endif %}">
            <a href="{% url 'final_challenge:query_one' %}">
              <i class="tim-icons icon-chart-pie-36"></i>
              <p>Consulta 1</p>
            </a>
          </li>
          <li class="{% if 'icons' in segment %} active {% endif %}">
            <a href="{% url 'final_challenge:query_two' %}">
              <i class="tim-icons icon-atom"></i>
              <p>Consulta 2</p>
            </a>
          </li>
          <li class="{% if 'maps' in segment %} active {% endif %}">
            <a href="{% url 'final_challenge:query_three' %}">
              <i class="tim-icons icon-pin"></i>
              <p>Consulta 3</p>
            </a>
          </li>
          <li class="{% if 'notifications' in segment %} active {% endif %}">
            <a href="{% url 'final_challenge:query_four' %}">
              <i class="tim-icons icon-bell-55"></i>
              <p>Consulta 4</p>
            </a>
          </li>
          <li class="{% if 'page-user' in segment %} active {% endif %}">
            <a href="{% url 'final_challenge:query_five' %}">
              <i class="tim-icons icon-single-02"></i>
              <p>Consulta 5</p>
            </a>
          </li>
          <li class="{% if 'tables' in segment %} active {% endif %}">
            <a href="{% url 'final_challenge:query_six' %}">
              <i class="tim-icons icon-puzzle-10"></i>
              <p>Consulta 6</p>
            </a>
          </li>
          <li class="{% if 'typography' in segment %} active {% endif %}">
            <a href="{% url 'final_challenge:query_seven' %}">
              <i class="tim-icons icon-align-center"></i>
              <p>Consulta 7</p>
            </a>
          </li>
          <li class="{% if 'rtl-support' in segment %} active {% endif %}">
            <a href="{% url 'final_challenge:query_eight' %}">
              <i class="tim-icons icon-world"></i>
              <p>Consulta 8</p>
            </a>
          </li>
          <li>
            <a href="{% url 'final_challenge:query_nine' %}" >
              <i class="tim-icons icon-button-power"></i>
              <p>Consulta 9</p>
            </a>
          </li>
          {% else %}
          <li class="active">
            <a target="_blank" 
               href="https://appseed.us/admin-dashboards/django-dashboard-black-pro">
              <i class="tim-icons icon-spaceship"></i>
              <p>PRO Version</p>
            </a>
          </li>   
          {% endif %}
                    
        </ul>
        
      </div>
    </div>